import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local"; // import local font
import "./globals.css";
import Providers from "./Providers";

// Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Local Eras ITC font
const erasFont = localFont({
  src: "../public/fonts/ERASMD.ttf", // make sure this path is correct
  display: "swap",
  variable: "--font-eras", // optional CSS variable
});

export const metadata = {
  title: "ChatBot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${erasFont.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
